NAME = serialize
CXX = c++
CXXFLAGS = -Wall -Wextra -Werror -std=c++98
SRC = serializer.cpp main.cpp
OBJ = $(SRC:.cpp=.o)
RM = rm -f
all: $(NAME)

$(NAME):$(OBJ)
	$(CXX) $(CXXFLAGS) $(OBJ) -o $(NAME)

clean: 
	$(RM) $(OBJ)

fclean: clean
	$(RM) $(NAME)

re: fclean all

.PHONY: all clean fclean re
